matrix:
  include:
    - language: sass
      before_install:
        - gem install sass
      script:
        - test/ruby-sass.sh
    - language: node_js
      node_js:
        - node
      before_script:
        - npm i -g sass
      script:
        - node test/dart-sass.js
