# Meta

title:         "Bulma: a modern CSS framework based on Flexbox"
description:   "Bulma is a CSS framework based on Flexbox and built with Sass"

# Build

encoding:      UTF-8
markdown:      kramdown
permalink:     pretty
source:        docs
url:           "http://bulma.io"

# Variables

baseurl:       ""
cssurl:        "/styles/bulma-website.css"
documentation: "/documentation/overview/start/"
download:      "https://github.com/jgthms/bulma/archive/0.1.2.zip"
github:        "https://github.com/jgthms/bulma"
version:       0.1.2
